FROM python:3.10-slim
COPY ./instantclient-basic-linux.x64-11.2.0.4.0.zip /tmp/
RUN apt-get update && \
        apt-get install libaio1 unzip -y && \
        mkdir -p /opt/oracle && \
    unzip /tmp/instantclient-basic-linux.x64-11.2.0.4.0.zip -d /opt/oracle && \
    mv /opt/oracle/instantclient_11_2 /opt/oracle/instantclient && \
    ln -s /opt/oracle/instantclient/libclntsh.so.11.1 /opt/oracle/instantclient/libclntsh.so && \
    ln -s /opt/oracle/instantclient/libocci.so.11.1 /opt/oracle/instantclient/libocci.so && \
    rm -rf /tmp/instantclient* && \
        echo '/opt/oracle/instantclient/' | tee -a /etc/ld.so.conf.d/oracle_instant_client.conf && ldconfig && \
        mkdir -p /opt/oracle/instantclient/network/admin
ENV LANG="en_US.UTF-8" TZ="Asia/Shanghai" \
    ORACLE_HOME=/opt/oracle/instantclient \
    TNS_ADMIN=$ORACLE_HOME/network/admin \
    PATH=$PATH:$ORACLE_HOME/bin \
    LD_LIBRARY_PATH=/opt/oracle/instantclient:$ORACLE_HOME
USER root
WORKDIR /
CMD ["/bin/bash"]
